### ISSUE TITLE
Invalid verification status: Request id limit reached

### ISSUE THREAD

**Issue by itzjustalan** [truecaller/flutter-sdk#13]
Haven't done even one successful otp verification yet it gives this internal server error with status code 2.
verifying true caller users works fine tho.

**Comment by parth0907** [comment]
Hi @itzjustalan 


For security reasons and to prevent request abuse, we have enforced a throttling limit on the number of verification attempts that are allowed for a per number and device combination.

The limit gets reset automatically every 24 hours. The limit is pretty generous and wouldn't impact your real users. It usually happens only during testing phase that you face such error.

Also, in case of any technical/flow related questions, please feel free to reach via our support channel https://developer.truecaller.com/support for a faster and dedicated response.

Hope this helps!

Regrads,
Parth

**Comment by itzjustalan** [comment]
how can the limit be reached if not even one request was successful also couldn't find any reference to the exact limit any where on the website..

**Comment by parth0907** [comment]
Hi @itzjustalan 

As mentioned in our earlier comment, there are a total of 2 fresh verification attempts allowed per number and device combination. Any request to initiate a dropcall/SMS via the SDK is counted as fresh attempt. In your case, you might have hit throttling due to the failed attempts. Since the limit gets reset after 24 hours automatically, request you to try then.

Regards,
Parth

**Comment by itzjustalan** [comment]
Thanks for that clarification there was nothing like this in the documentation.

**Comment by ubarua123** [comment]
@parth0907 You guys should come up with a development mode. Allocate some pseudo phone numbers as well. The SDK can return pseudo success or failure returns. Don't really need to actually verify the phone number. That'll be done by the developer when the module coding is done and is ready for final testing. That should be done by testing the real phone number.
2 Attempts in 24 hours, really? Plus because of the lack of documentation, I didn't know this limit. And so thanks to you, I got delayed by 24 hours.

**Comment by parth0907** [comment]
Hi @ubarua123 

Hope you are doing great! 

Thanks for your valuable feedback, we will discuss this internally and see if something can be done around the pseudo implementation. Regarding the error cases, all of the details are mentioned in our documentation. Please find attached the link of the same : [here](https://github.com/truecaller/flutter-sdk#note). 

The limit is said to be 2 Attempts in 24 hours so as to prevent our internal system abuse. The limit is pretty generous and ideally should not impact your real users. The issue you are facing generally only happen during testing phase.

Let me know if there is any confusion or if there is something that you are not able to find in the documentation, I would be happy to pin point. 

Regards, 
Parth

**Comment by khemraj-chauhan** [comment]
I am facing the same problem what is mention by [ubarua123](https://github.com/ubarua123), most of the time truecaller is being used by truecaller users only but someone wants to integrate the full integration flow, the above problem comes in test mode, we have already registered test number on developer platform, so why this limit in test env?? or should be increase more atleast for test env.
