### ISSUE TITLE
Invalid partner credentials.

### ISSUE THREAD

**Issue by yogeshkaharmis** [truecaller/flutter-sdk#51]
hello
I am getting Invalid partner credentials error on truecaller flutter sdk using in project.
I am add SHA-1 key and project bundle id proper way then getting error.

package id - com.ls.agrisevakuser
client id - iw9kggeikv73mfwjmb9txyjen5nyi9gnstwrkekizuk  
SHA1 key - 33:C7:A8:9F:70:B9:A4:7E:4B:A8:0A:F3:AD:0F:95:01:1B:17:B4:D1
package  - truecaller_sdk: ^0.1.2

SHA1 key is system generated key.
Please help me. @shubhral 
thank you

**Comment by tahaf22labs** [comment]
Getting the same error. And I'm assuming its coz the old method is depreciated which was supported during 0.1.2,


<img width="1278" alt="image" src="https://github.com/user-attachments/assets/cd98221f-a6b4-41e6-97e0-0f48ef84d637">

**Comment by yogeshkaharmis** [comment]
hello
you can use latest version of truecaller SDK.

**Comment by tahaf22labs** [comment]
> hello you can use latest version of truecaller SDK.

The latest version of SDK Supports 3.0.0. Where as 0.1.2 is intended for old SDK (correct me if I'm wrong)

**Comment by yogeshkaharmis** [comment]
> The latest version of SDK Supports 3.0.0. Where as 0.1.2 is intended for old SDK 2.8.x (correct me if I'm wrong)

yes but if you want working, you use latest version of sdk.

**Comment by tahaf22labs** [comment]
> package id - com.ls.agrisevakuser

I guess you are not getting why yours is showing "Invalid partner credentials" 
v 0.1.2 relies on the old Dashboard's generated key (This used to give partner key). 
 But now since they have put the curtains down on that, we are now supposed to use newer version 1.0.0. with the new Dashboard's Client Key. 


If you look into the documentation, 0.1.2 Accepts "partnerKey" in the Manifest (com.truecaller.android.sdk.PartnerKey).
Whereas 1.0.0 requires "clientKey" (com.truecaller.android.sdk.ClientId)

**Comment by tahaf22labs** [comment]
> > The latest version of SDK Supports 3.0.0. Where as 0.1.2 is intended for old SDK 2.8.x (correct me if I'm wrong)
> 
> yes but if you want working, you use latest version of sdk.

I guess you are not getting why yours is showing "Invalid partner credentials" 
v 0.1.2 relies on the old Dashboard's generated key (This used to give partner key). 
 But now since they have put the curtains down on that, we are now supposed to use newer version 1.0.0. with the new Dashboard's Client Key. 


If you look into the documentation, 0.1.2 Accepts "partnerKey" in the Manifest (com.truecaller.android.sdk.PartnerKey).
Whereas 1.0.0 requires "clientKey" (com.truecaller.android.sdk.ClientId)

**Comment by yogeshkaharmis** [comment]
It is close.
thank you.

**Comment by yogeshkaharmis** [comment]
it is close.
thank you
