### ISSUE TITLE
Questions - Few questions related to verification

### ISSUE THREAD

**Issue by bajajsahil** [truecaller/flutter-sdk#9]
Hi,

I have 2 questions related to verification in case of no true caller app installed.

1. In the case of OTP verification, will it be a 4 digit OTP or 6 digit OTP?

2. After OTPReceived/MissedCallReceived, we have to verification by sending the first name and last name ```TruecallerSdk.verifyOtp("FIRST_NAME", "LAST_NAME", "OTP");```. But in our app, we don't have first and last names on the sign-up page. So, what would be an alternative to this?

Thanks in advance.

**Comment by bajajsahil** [comment]
Hi, Can I get an answer, please?

**Comment by singhalyogesh** [comment]
Hey @bajajsahil 
#1 The OTP sent by Truecaller SDK for verification purposes is of 6 digits

#2 In order to complete the verification flow, the SDK expects first name and last name of the user. This is a mandatory step and is required to enable a seamless experience for the users when they return to your app again in future. For all future verification attempts for the same user on their device, Truecaller SDK enables a "direct verification" without need for any OTP or drop call, and in return you also get access to the same user identity details in the response, which were passed in the original verification to the SDK. This ensures the users don't need to provide their details again once they have been verified previously.

**Comment by bajajsahil** [comment]
Thanks @singhalyogesh

**Comment by bajajsahil** [comment]
Sorry, I am reopening it again. I have one more doubt. 

Rapido is using the Truecaller SDK and I found they are validating the OTP on the OTP screen only.  How they are verifying it without first name and last name because first name and last name we are entering on next sceen to OTP. 

Is there any exclusive method for validating the OTP alone?

**Comment by singhalyogesh** [comment]
Our partner app Rapido is using Truecaller SDK's drop call flow only, and not the OTP flow.
They use Truecaller SDK's drop call flow to verify the users ( who don't have Truecaller app on their device ) on their first attempt, and if that fails they have their own fallback OTP mechanism in place. Hope this clarifies

**Comment by singhalyogesh** [comment]
On another note, in case of any technical/flow related questions, please feel free to reach via our support channel https://developer.truecaller.com/support for a faster and dedicated response. @bajajsahil

**Comment by bajajsahil** [comment]
Thanks @singhalyogesh . It clarified the doubts. I will check the support for similar questions going forward.
